export const INCREMENT = 'INCREMENT'

export const DECREMENT = 'DECREMENT'

export const ASYNC_INCREMENT = 'ASYNC_INCREMENT'

export const CART_PRODUCT_COUNT = 'CART_PRODUCT_COUNT'

export const ADD_PRODUCT = 'ADD_PRODUCT'

export const DECREASE_PRODUCT = 'DECREASE_PRODUCT'

export const UPDATE_PRODUCT_INFO = 'UPDATE_PRODUCT_INFO'