export const baseUrl = 'https://vip-test.steedos.com:8443'
// export const baseUrl = 'http://steedos.ticp.net:3086'
export const demoSpaceId = 'hSGPc2fsMAp9NDcHy'
export const demoStoreId = 'B2k7E62gWg8DXBztn'
export const appId = 'wx89eb02efdb4ddaaf'
