export const baseUrl = 'https://vip-test.steedos.com:8443'
// export const baseUrl = 'https://vip-beta.steedos.com'
export const demoSpaceId = 'hSGPc2fsMAp9NDcHy'
export const demoStoreId = 'B2k7E62gWg8DXBztn'
export const appId = 'wx89eb02efdb4ddaaf'
export const baseMaterialUrl = 'https://lg-769qcuso-1253849369.cos.ap-shanghai.myqcloud.com/'
export const aliyunOSSEndpoint = 'https://sand-vip.oss-cn-beijing.aliyuncs.com/'
